In [36]:
# CodeGrade step0
import pandas as pd
import sqlite3

conn1 = sqlite3.connect('planets.db')
conn2 = sqlite3.connect('dogs.db')
conn3 = sqlite3.connect('babe_ruth.db')

In [37]:
# CodeGrade Step 1
df_no_moons = pd.read_sql("""
SELECT *
FROM planets
WHERE num_of_moons = 0;
""", conn1)

In [8]:
# CodeGrade step2
df_name_seven = pd.read_sql("""
SELECT name, mass
FROM planets
WHERE LENGTH(name) = 7;
""", conn1)

In [9]:
# CodeGrade step3
df_mass = pd.read_sql("""
SELECT name, mass
FROM planets
WHERE mass <= 1.00;
""", conn1)

In [26]:
pd.read_sql("PRAGMA table_info(planets);", conn1)

   cid          name     type  notnull dflt_value  pk
0    0            id  INTEGER        0       None   1
1    1          name     TEXT        0       None   0
2    2         color     TEXT        0       None   0
3    3  num_of_moons  INTEGER        0       None   0
4    4          mass     REAL        0       None   0
5    5         rings  BOOLEAN        0       None   0

In [27]:
# CodeGrade step4
df_mass_moon = pd.read_sql("""
SELECT *
FROM planets
WHERE num_of_moons >= 1
  AND mass < 1.00;
""", conn1)

In [11]:
# CodeGrade step5
df_blue = pd.read_sql("""
SELECT name, color
FROM planets
WHERE color LIKE '%blue%';
""", conn1)

In [16]:
# CodeGrade step6
df_hungry = pd.read_sql("""
SELECT name, age, breed
FROM dogs
WHERE hungry = 1
ORDER BY age ASC;
""", conn2)

In [17]:
# CodeGrade step7
df_hungry_ages = pd.read_sql("""
SELECT name, age, hungry
FROM dogs
WHERE hungry = 1
  AND age BETWEEN 2 AND 7
ORDER BY name ASC;
""", conn2)

In [18]:
# CodeGrade step7
df_hungry_ages = pd.read_sql("""
SELECT name, age, hungry
FROM dogs
WHERE hungry = 1
  AND age BETWEEN 2 AND 7
ORDER BY name ASC;
""", conn2)

In [19]:
# CodeGrade step8
df_4_oldest = pd.read_sql("""
SELECT name, age, breed
FROM (
    SELECT name, age, breed
    FROM dogs
    ORDER BY age DESC
    LIMIT 4
)
ORDER BY breed ASC;
""", conn2)

In [31]:
# CodeGrade step9
df_ruth_years = pd.read_sql("""
SELECT COUNT(*) AS total_years
FROM babe_ruth_stats;
""", conn3)

In [32]:
# CodeGrade step10
df_hr_total = pd.read_sql("""
SELECT SUM(HR) AS total_homeruns
FROM babe_ruth_stats;
""", conn3)

In [33]:
# CodeGrade step11
df_teams_years = pd.read_sql("""
SELECT team, COUNT(*) AS number_years
FROM babe_ruth_stats
GROUP BY team;
""", conn3)

In [29]:
pd.read_sql("PRAGMA table_info(babe_ruth_stats);", conn3)

    cid     name     type  notnull dflt_value  pk
0     0       id  INTEGER        0       None   1
1     1     year  INTEGER        0       None   0
2     2     team     TEXT        0       None   0
3     3   league     TEXT        0       None   0
4     4  doubles  INTEGER        0       None   0
5     5  triples  INTEGER        0       None   0
6     6     hits  INTEGER        0       None   0
7     7       HR  INTEGER        0       None   0
8     8    games  INTEGER        0       None   0
9     9     runs  INTEGER        0       None   0
10   10      RBI  INTEGER        0       None   0
11   11  at_bats  INTEGER        0       None   0
12   12       BB  INTEGER        0       None   0
13   13       SB  INTEGER        0       None   0
14   14       SO  INTEGER        0       None   0
15   15      AVG     REAL        0       None   0

In [35]:
# CodeGrade step12
df_at_bats = pd.read_sql("""
SELECT team, AVG(at_bats) AS average_at_bats
FROM babe_ruth_stats
GROUP BY team
HAVING AVG(at_bats) > 200;
""", conn3)